server:
  port: 10005

spring:
  application:
    name: spring-ai-alibaba-ark-chat-model-example
  ai:
    openai:
      # API Key Configuration
      api-key: ${OPENAI_API_KEY}
      # Ark LLM API Base URL
      base-url: https://ark.cn-beijing.volces.com/api/
      chat:
        options:
          # Model ID, replace with actual access point ID
          model: ${OPENAI_MODEL_ID}
        # Chat API path, consistent with OpenAI interface
        completions-path: /v3/chat/completions 