spring:
  application:
    name: prompt-example

  ai:
    dashscope:
      agent:
        app-id: 3396899830464ce0ad873bc20b783264
      api-key: ${AI_DASHSCOPE_API_KEY}
      #workspace-id: ${AI_DASHSCOPE_WORKSPACE_ID} #选填，如果不填写，则默认使用应用的默认工作区