server:
  port: 10014

spring:
  application:
    name: more-client-examples

  ai:
    dashscope:
      chat:
        api-key: ${AI_DASHSCOPE_API_KEY}

    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
